In [108]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Context
"Predict behavior to retain customers. You can analyze all relevant customer data and develop focused customer retention programs." [IBM Sample Data Sets]

Content
Each row represents a customer, each column contains customer’s attributes described on the column Metadata.

The data set includes information about:

Customers who left within the last month – the column is called Churn
Services that each customer has signed up for – phone, multiple lines, internet, online security, online backup, device protection, tech support, and streaming TV and movies
Customer account information – how long they’ve been a customer, contract, payment method, paperless billing, monthly charges, and total charges
Demographic info about customers – gender, age range, and if they have partners and dependents
Inspiration
To explore this type of models and learn more about the subject.

# Steps

* Exploratory Data Analysis

In [109]:
df = pd.read_csv("../input/telco-customer-churn/WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head()

1. The Data Set has 20 features 
2. As per the problem case we dont need customer ID for now

In [110]:
# Removing the CustomerID Column form the data Frame
df.drop("customerID", axis=1, inplace = True)  
df.head()

In [111]:
df.dtypes

In [112]:
df.describe()

In [113]:
df.info()

In [114]:
df.TotalCharges.values

In [115]:
df.MonthlyCharges.values

* We can see that 'TotalCharges' is in string type while 'MonthlyCharges' are in floating point type
* So naturally its necessary to change 'TotalCharges' column into Numeric type

In [116]:
pd.to_numeric(df.TotalCharges, errors='coerce').isnull()

In [117]:
df[pd.to_numeric(df.TotalCharges, errors='coerce').isnull()]

# This will show us the rows which contains Null values in 'TotalCharges'

In [118]:
df[pd.to_numeric(df.TotalCharges, errors='coerce').isnull()].shape

* There are on;ly 11 rows which are Null out of 7043 rows
* To keep things simple we can just drop these rows because its comprises a mere 0.15% of the total rows

In [119]:
df1 = df[df.TotalCharges !=' ']  ## Droping the Rows which are null 
df1.shape

https://www.youtube.com/watch?v=MSBY28IJ47U

In [120]:
df1.TotalCharges = pd.to_numeric(df1.TotalCharges) # Storing the converted numeric column into df1

In [121]:
df1.TotalCharges
df1.info()

# Time for some quick Visualization

## Features to consider for Visualization

 0. gender            
 1. SeniorCitizen     
 2. Partner         
 3. Dependents        
 4. tenure           
 5. PhoneService      
 6. MultipleLines      
 7. InternetService

### Lets Consider Tenure first

> A tenure of a customer can say about their Loyality towards a service provider

* So lets break down Tenure into Churn & no churn, 2 seperate data frames
* Where, 'No' means the customer is leaving while 'Yes' means the customer is not leaving

In [122]:
tenure_churn_no = df1[df1.Churn == 'No'].tenure
tenure_churn_yes = df1[df1.Churn == 'Yes'].tenure

In [151]:
# Lets PLot a simple histogram


plt.figure(figsize=(11,8))
plt.xlabel('Tenure')
plt.ylabel('No. of customer')
plt.title('Histogram of Customer Churn')
plt.hist([tenure_churn_no,tenure_churn_yes], color = ['green','orange'], label = ['Churn = Yes', 'Churn = No'])
plt.legend()

* We can observe that the maximum number of customers which have high churn rate is higher where the Tenure is more than 65 months